src/Entity/RelativeHasMedic.php
<?php

namespace App\Entity;

use App\Repository\RelativeHasMedicRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=RelativeHasMedicRepository::class)
 */
class RelativeHasMedic
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $dose;

    /**
     * @ORM\Column(type="integer")
     */
    private $nb_times;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $endAt;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $comment;

    /**
     * @ORM\ManyToOne(targetEntity=Medic::class, inversedBy="relativeHasMedics")
     * @ORM\JoinColumn(nullable=false)
     */
    private $medicId;

    /**
     * @ORM\ManyToOne(targetEntity=Relative::class, inversedBy="relativeHasMedics")
     * @ORM\JoinColumn(nullable=false)
     */
    private $relativeId;

    /**
     * @ORM\OneToMany(targetEntity=TreatmentHour::class, mappedBy="hasMedicId")
     */
    private $treatmentHours;

    public function __construct()
    {
        $this->treatmentHours = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDose(): ?int
    {
        return $this->dose;
    }

    public function setDose(int $dose): self
    {
        $this->dose = $dose;

        return $this;
    }

    public function getNbTimes(): ?int
    {
        return $this->nb_times;
    }

    public function setNbTimes(int $nb_times): self
    {
        $this->nb_times = $nb_times;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getEndAt(): ?\DateTimeInterface
    {
        return $this->endAt;
    }

    public function setEndAt(?\DateTimeInterface $endAt): self
    {
        $this->endAt = $endAt;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }

    public function getMedicId(): ?Medic
    {
        return $this->medicId;
    }

    public function setMedicId(?Medic $medicId): self
    {
        $this->medicId = $medicId;

        return $this;
    }

    public function getRelativeId(): ?Relative
    {
        return $this->relativeId;
    }

    public function setRelativeId(?Relative $relativeId): self
    {
        $this->relativeId = $relativeId;

        return $this;
    }

    /**
     * @return Collection|TreatmentHour[]
     */
    public function getTreatmentHours(): Collection
    {
        return $this->treatmentHours;
    }

    public function addTreatmentHour(TreatmentHour $treatmentHour): self
    {
        if (!$this->treatmentHours->contains($treatmentHour)) {
            $this->treatmentHours[] = $treatmentHour;
            $treatmentHour->setHasMedicId($this);
        }

        return $this;
    }

    public function removeTreatmentHour(TreatmentHour $treatmentHour): self
    {
        if ($this->treatmentHours->contains($treatmentHour)) {
            $this->treatmentHours->removeElement($treatmentHour);
            // set the owning side to null (unless already changed)
            if ($treatmentHour->getHasMedicId() === $this) {
                $treatmentHour->setHasMedicId(null);
            }
        }

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $resetToken;

    /**
     * @ORM\Column(type="string", length=6, nullable=true)
     */
    private $zipCode;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified;

    /**
     * @ORM\OneToMany(targetEntity=Relative::class, mappedBy="userId", cascade={"persist"})
     */
    private $relatives;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isDoctor;

    public function __construct()
    {
        $this->relatives = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getResetToken(): ?string
    {
        return $this->resetToken;
    }

    public function setResetToken(?string $resetToken): self
    {
        $this->resetToken = $resetToken;

        return $this;
    }

    public function getZipCode(): ?string
    {
        return $this->zipCode;
    }

    public function setZipCode(?string $zipCode): self
    {
        $this->zipCode = $zipCode;

        return $this;
    }

    public function getIsVerified(): ?bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    /**
     * @return Collection|Relative[]
     */
    public function getRelatives(): Collection
    {
        return $this->relatives;
    }

    public function addRelative(Relative $relative): self
    {
        if (!$this->relatives->contains($relative)) {
            $this->relatives[] = $relative;
            $relative->setUserId($this);
        }

        return $this;
    }

    public function removeRelative(Relative $relative): self
    {
        if ($this->relatives->contains($relative)) {
            $this->relatives->removeElement($relative);
            // set the owning side to null (unless already changed)
            if ($relative->getUserId() === $this) {
                $relative->setUserId(null);
            }
        }

        return $this;
    }

    public function getIsDoctor(): ?bool
    {
        return $this->isDoctor;
    }

    public function setIsDoctor(bool $isDoctor): self
    {
        $this->isDoctor = $isDoctor;

        return $this;
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\Relative;
use App\Entity\User;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class UserController extends AbstractController
{
    /**
     * @Route("/user", name="user")
     */
    public function index()
    {
        return $this->render('user/index.html.twig', [
            'controller_name' => 'UserController',
        ]);
    }

    /**
     * @Route("/user/{id}", name="user_show", methods={"GET"})
     * @Route("/user/{id}/relative/{relative}", name="user_show_relative")
     */
    public function show(User $user, ?Relative $relative) :Response
    {
        if (!empty($relative)) {
            return $this->render('user/index.html.twig', [
                'user' => $user,
                'relative_medoc' => $relative
            ]);
        }
        return $this->render('user/index.html.twig', [
            'user' => $user,
        ]);
    }
}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello UserController!{% endblock %}

{% block body %}
    <div class="container-profil">
        <div class="left-side">
            <h1>Whose care ?</h1>
            {% for relative in user.relatives  %}
                    <div class="relative-card {% if relative_medoc is defined and relative_medoc.id == relative.id%} card-active {% endif %}">
                        <a href="{{ path('user_show_relative', {'id': user.id, 'relative': relative.id}) }}">
                        <div class="relative-info">
                            <h3>{{ relative.firstName}} </h3>
                            <p>{{ relative.birthdate|date("m/d/Y") }}</p>
                        </div>
                        </a>
                    </div>
            {% endfor %}
            {% if app.user.isDoctor == 0 %}
                <div class="add-relative">
                    <a href="{{ path('relative_new') }}">
                        <svg class="navbar-svg">
                            <use xlink:href="/img/user-plus-solid.svg#add"></use>
                        </svg>
                    </a>
                </div>
            {% endif %}

        </div>
        <div class="right-side">
            <h1>
                {% if relative_medoc is defined %}
                    {{ relative_medoc.firstName ~ "'s" }} treatment
                {% endif %}
            </h1>
            <div class="medoc">
                {% if app.user.isDoctor == 1 %}
                    <table>
                        <thead>
                        <tr class="head-table">
                            <th>Name</th>
                            <th>Dose</th>
                            <th>Per/Days</th>
                            <th>Comment</th>
                            <th>Image</th>
                            {% if app.user.isDoctor == 1 %}
                                <th>Action</th>
                            {% endif %}
                        </tr>
                        </thead>
                        <tbody class="body-table">
                        {% if relative_medoc is defined %}
                            {% for medoc in relative_medoc.relativeHasMedics  %}
                                <tr>
                                    <td class="name">{{ medoc.medicId.name }}</td>
                                    <td class="dose">{{ medoc.dose }}</td>
                                    <td class="perdays">{{ medoc.nbTimes }}</td>
                                    <td class="comment">{{ medoc.comment }}</td>
                                    <td class="image"><img src="{{ medoc.medicId.image }}"></td>
                                    {% if app.user.isDoctor == 1 %}
                                        <td class="action">
                                            <ul class="action-list">
                                                {{ include('relative_has_medic/_delete_form.html.twig') }}
                                                {#<li><a class="delete-link" href="{{ path('relative_has_medic_delete', {'id': medoc.id}) }}">Delete</a></li> #}
                                                <li><a href="{{ path('relative_has_medic_edit', {'id': medoc.id}) }}">Edit</a></li>
                                            </ul>
                                        </td>
                                    {% endif %}
                                </tr>
                            {% endfor %}
                        {% endif %}
                        </tbody>
                    </table>
                {% else %}
                <ul>
                    {% if relative_medoc is defined %}
                        {% for medoc in relative_medoc.relativeHasMedics  %}
                            <li class="pill-container" >{{ medoc.medicId.name ~ ': ' ~ medoc.dose ~ ' pill ' ~ medoc.nbTimes ~ ' per days' }}<img class="pill" src="{{ medoc.medicId.image }}"></li>
                        {% endfor %}
                    {% endif %}
                </ul>
                {% endif %}


            </div>
            {% if app.user.isDoctor == 1 and relative_medoc is defined %}
                <div class="add-medoc">
                    <a href="{{ path('relative_has_medic_new', {'id': relative_medoc.id }) }}">Add treatment</a>
                </div>
            {% endif %}
        </div>
    </div>


{% endblock %}